### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by maxrjones** [xarray-contrib/xbatcher#104]
### What is your issue?

There's been some good progress on xbatcher since the last release over a year ago. @weiji14 mentioned a second release at the Pangeo ML meeting on Monday. I'm opening this issue to suggest a revised target date and track progress on the remaining tasks. Please comment with any items that should be considered for the release.

Proposed release date: **October 26, 2022**

To-do:
- [x] https://github.com/xarray-contrib/xbatcher/pull/103
- [x] https://github.com/xarray-contrib/xbatcher/pull/100
- [x] Let TensorFlow accessor and data loader handle either xarray.DataArray or xarray.Dataset inputs ([https://github.com/xarray-contrib/xbatcher/issues/83 part 1](https://github.com/xarray-contrib/xbatcher/pull/107))
- [x] https://github.com/xarray-contrib/xbatcher/pull/108
- [x] https://github.com/xarray-contrib/xbatcher/pull/112

**Comment by maxrjones** [comment]
Just a note that since the [0.1.0 tag](https://github.com/xarray-contrib/xbatcher/releases/tag/0.1.0) wasn't accompanied by a [GitHub release](https://github.com/xarray-contrib/xbatcher/releases), we'll need to be careful when publishing the release notes to make sure it's associated with a new 0.2.0 tag rather than the existing 0.1.0 tag.

**Comment by weiji14** [comment]
Since we're overdue on the release already by a week, is it possible to wait for #112 to be merged first :pleading_face:?

**Comment by maxrjones** [comment]
> Since we're overdue on the release already by a week, is it possible to wait for https://github.com/xarray-contrib/xbatcher/pull/112 to be merged first 🥺?

Yes, I agree that it would be best to wait for that. In particular since the `_gen_batches` call was actually moved to `__init__` since the last release, so that PR addresses an unreleased performance regression

**Comment by dhruvbalwada** [comment]
I would really like if #43 can be resolved too. 
Would be happy to contribute an example for this, if there is some guidance on how to tackle this.

**Comment by maxrjones** [comment]
Just need to verify that https://github.com/xarray-contrib/xbatcher/pull/119 didn't break the long description rendering for PyPI and then I think we're ready for the release. Thanks for your patience!
