### ISSUE TITLE
Show version snapshots in xbatcher's readthedocs page

### ISSUE THREAD

**Issue by weiji14** [xarray-contrib/xbatcher#135]
### Is your feature request related to a problem?

Currently at https://xbatcher.readthedocs.io/en/latest/api.html, there are only 'latest' and 'stable' versions of the documentation to switch between. With 'latest' being what's on xbatcher's 'main' branch, and 'stable' being the last release (v0.2.0).

![image](https://user-images.githubusercontent.com/23487320/205691699-20c53b71-38a5-41c4-9623-1e8031254063.png)

### Describe the solution you'd like

Each tagged version should have it's own documentation page. E.g. in `xarray` at https://docs.xarray.dev/en/v2022.12.0, it is possible to show the documentation for different release versions
![image](https://user-images.githubusercontent.com/23487320/205692252-9a48481b-f440-4fd4-aa21-e6c29ac45a4a.png)

This helps when there are significant API changes (which might be coming up in future `xbatcher` releases), and people need to refer back to older versions like v0.1.0.

### Describe alternatives you've considered

Keep the status quo of just 'latest' and 'stable'.

### Additional context

The readthedocs setting is documented at https://docs.readthedocs.io/en/stable/versions.html. If I'm not mistaken, it should involve unchecking the 'Single version' box at https://readthedocs.org/dashboard/xbatcher/advanced?

![image](https://user-images.githubusercontent.com/23487320/205693612-f80dc33d-b3d8-4efb-8d80-45c00491af6b.png)

Also, it should be possible to build previous tagged versions (v0.1.0, v0.2.0) at https://readthedocs.org/projects/xbatcher/versions/

**Comment by maxrjones** [comment]
Seems like a good idea to me! That box is already unchecked, but I could look into this more or add you to the project on readthedocs if you're interested in working on it.

**Comment by weiji14** [comment]
Hmm, maybe the setting is somewhere else. If you add me as a maintainer (my readthedocs username is same as on GitHub), I'll try to find it. I knew I had to do it in https://github.com/weiji14/zen3geo/pull/13, but forgot exactly how :sweat_smile:

**Comment by weiji14** [comment]
Thanks Max for the invite! I think I've figured it out, the steps are:
1. Go to https://readthedocs.org/projects/xbatcher/versions/
2. Under 'Activate a version', select a tag (e.g. `v0.2.0`) and click on 'Activate'
3. Check the 'Activate' box and click 'Save'
   ![Activating the v0.2.0 docs build](https://user-images.githubusercontent.com/23487320/206790982-f2dadda9-876c-4a02-bb0d-5f2ad2cdcbed.png)
4. Wait for the tagged versions to build, see progress under https://readthedocs.org/projects/xbatcher/builds
    ![Builds triggered for tags v0.2.0 and 0.1.0](https://user-images.githubusercontent.com/23487320/206791296-055d80bf-6e26-41b9-9e12-e5b4ca3e4810.png)
 
Not sure if we have to manually trigger this for every tagged release (I don't recall having to do it for zen3geo), but yeah, here are the tagged builds:

- https://xbatcher.readthedocs.io/en/0.1.0/
- https://xbatcher.readthedocs.io/en/v0.2.0/

Closing this issue as completed.

**Comment by maxrjones** [comment]
Super, thanks @weiji14!

**Comment by maxrjones** [comment]
reopening in order to add the version switcher to the pydata theme configuration (https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html#version-switcher-dropdowns)

**Comment by maxrjones** [comment]
Fixed by https://github.com/xarray-contrib/xbatcher/pull/152
