### ISSUE TITLE
Should we transfer this project to the xarray-contrib org?

### ISSUE THREAD

**Issue by jhamman** [xarray-contrib/xbatcher#86]
### What is your issue?

I've been wondering if xbatcher would be more at home in the xarray-contrib GitHub organization. It already meets all of the requirements and would likely get broader visibility there.

Thoughts from @maxrjones, @rabernat, @weiji14, @cmdupuis3, or others?

**Comment by maxrjones** [comment]
I agree that the xarray-contrib organization would be a better fit. I did not notice any prohibitive downsides reading through https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by jhamman** [comment]
Yes, we don't have templates set up yet but here's a good issue to model after. https://github.com/xarray-contrib/xarray-contrib/issues/8

**Comment by weiji14** [comment]
Ah ok, that's helpful. I can set up a template first for https://github.com/xarray-contrib/xarray-contrib/issues/3 using https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema, give me a few minutes.

**Comment by maxrjones** [comment]
Thanks for creating the issue template @weiji14! I opened an issue to start the transfer process over at https://github.com/xarray-contrib/xarray-contrib/issues/10.

**Comment by maxrjones** [comment]
Thanks @jhamman for handling the transfer!

The last step will be to update the code of conduct since it doesn't make much sense to fall back to the Pangeo code of conduct anymore. I suggest that we update it to use the contributor covenant v2.1, which is fairly standard.

FYI it's recommended to update local clones to point to the new repository URL, even though redirects are supported. Here's the command for that (assuming you've named the remote `origin`):
```
git remote set-url origin git@github.com:xarray-contrib/xbatcher.git
```
or 
```
git remote set-url origin https://github.com/xarray-contrib/xbatcher.git
```

**Comment by jhamman** [comment]
@maxrjones - I did add an org wide code of conduct here: https://github.com/xarray-contrib/.github/pull/1

**Comment by maxrjones** [comment]
> @maxrjones - I did add an org wide code of conduct here: https://github.com/xarray-contrib/.github/pull/1

Great, thank you!
