### ISSUE TITLE
Xbatcher abstract for AMS 2023

### ISSUE THREAD

**Issue by maxrjones** [xarray-contrib/xbatcher#91]
### What is your issue?

I plan to submit an abstract on xbatcher to the [13th Symposium on Advances in Modeling and Analysis Using Python](https://annual.ametsoc.org/index.cfm/2023/program-events/conferences-and-symposia/13th-symposium-on-advances-in-modeling-and-analysis-using-python/) at AMS 2023 under "New Python Tools in the Atmospheric and Oceanographic Sciences".

Here's a draft abstract - https://hackmd.io/@maxrjones/ryEPfY91i.

@xarray-contrib/xbatcher-devs and other contributors, please add yourself to the abstract if you'd like to be listed as an author. Suggestions are also welcome. The abstract is due tomorrow, August 31 but authorship edits should still be possible afterwards.

**Comment by weiji14** [comment]
Neither an atmospheric scientist nor oceanographer, but I'll make sure to contribute more to xbatcher before 2023 :laughing:  The draft abstract looks good, just made a few minor changes and comments.

**Comment by rabernat** [comment]
Just stating explicitly that I am very happy to see this happen and I don't feel the need to be a co-author.

**Comment by maxrjones** [comment]
Thanks for the input - I just submitted the abstract but will leave this issue open for a while for visibility.

**Comment by maxrjones** [comment]
We've been assigned a talk at 6:30 PM MT on Wednesday, January 11 2023 - https://ams.confex.com/ams/103ANNUAL/meetingapp.cgi/Paper/420946

**Comment by jhamman** [comment]
> We've been assigned a talk at 6:30 PM MT on Wednesday, January 11 2023 - https://ams.confex.com/ams/103ANNUAL/meetingapp.cgi/Paper/420946

Though it doesn't say online, I think the timezone is local. So the scheduled time is 4:30p MT.

**Comment by maxrjones** [comment]
> > We've been assigned a talk at 6:30 PM MT on Wednesday, January 11 2023 - https://ams.confex.com/ams/103ANNUAL/meetingapp.cgi/Paper/420946
> 
> Though it doesn't say online, I think the timezone is local. So the scheduled time is 4:30p MT.

Thanks for pointing this out, I didn't notice the 'My Time' setting in the program viewer. 4:30 is a much better time.

<img src="https://user-images.githubusercontent.com/14077947/196270550-82a3416c-994a-43d0-add7-a9af024d13d8.png" width=200 align=left>
