### ISSUE TITLE
Clarify xbatcher license

### ISSUE THREAD

**Issue by maxrjones** [xarray-contrib/xbatcher#99]
### What is your issue?

The license file for xbatcher is MIT, but the [package metadata](https://github.com/xarray-contrib/xbatcher/blob/57cb69c8860b620dd7193c0fd197b39ecccf5d92/setup.py#L8-L14) lists Apache. @rabernat, as the original author can you confirm the correct license for xbatcher? I can update accordingly afterwards.

**Comment by jhamman** [comment]
I favor the Apache license for projects with multiple contributors. Therefore, I suggest we change the license file to the Apache license to line up with the package metadata.

**Comment by weiji14** [comment]
Does this count as relicensing? I would have thought the LICENSE file is the correct source, but looking at `git blame`, the 'Apache' license metadata added 28 Oct 2018
 at https://github.com/xarray-contrib/xbatcher/blame/a36a958d709900eb5dc6af700e0d21b22f3e55ed/setup.py#L14 actually came before the 'MIT' license file added on 4 Nov 2018
in 3e71e4473022c400e9d5edabff170e254a1b1a30, so not sure what's the original intention. Maybe wait for Ryan to clarify things :slightly_smiling_face:

**Comment by maxrjones** [comment]
My intuition was the same as yours that the LICENSE file would have taken precedence, but I'm not a lawyer either... As you suggested, we can wait for clarification about the intention here in order to determine whether this was a bug. Relicensing would be complicated but not impossible given the number of contributors.

**Comment by rabernat** [comment]
Sorry for the slow reply. Really no strong preference from me. I created this in a hurry without giving too much thought to the license. I support whatever path is easiest / preferred by the current contributors.
